<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.yangaobo</groupId>
    <artifactId>my-lesson</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>ml-common</module>
        <module>tools/ml-generator</module>
        <module>ml-gateway</module>
        <module>ml-user</module>
        <module>ml-course</module>
        <module>ml-sale</module>
        <module>ml-order</module>
        <module>ml-barrage</module>
        <module>ml-agent-relay</module>
        <module>ml-ai-search</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.2.5</spring-boot.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.0</spring-cloud-alibaba.version>
        <micrometer-tracing.version>1.0.4</micrometer-tracing.version>
        <junit.version>4.13.2</junit.version>
        <lombok.version>1.18.24</lombok.version>
        <hutool.version>5.8.25</hutool.version>
        <easyexcel.version>3.3.4</easyexcel.version>
        <minio.version>3.0.10</minio.version>
        <okio.version>3.5.0</okio.version>
        <hibernate-validator.version>8.0.1.Final</hibernate-validator.version>
        <jjwt.version>0.9.1</jjwt.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <mybatis-flex.version>1.10.2</mybatis-flex.version>
        <mybatis-flex-codegen.version>1.10.1</mybatis-flex-codegen.version>
        <knife4j.version>4.4.0</knife4j.version>
        <mysql.version>8.2.0</mysql.version>
        <feign-micrometer.version>12.3</feign-micrometer.version>
        <xxl-job.version>2.4.2</xxl-job.version>
        <qrcode.version>3.3.3</qrcode.version>
        <alipay-easysdk.version>2.2.0</alipay-easysdk.version>
        <aliyun-phone-verification.version>2.0.0</aliyun-phone-verification.version>
        <httpclient.version>4.5.13</httpclient.version>
        <redisson-spring-boot-starter.version>3.33.0</redisson-spring-boot-starter.version>
        <rocketmq-spring-boot-starter.version>2.2.2</rocketmq-spring-boot-starter.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <!--spring-boot-starter-parent-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--spring-cloud-dependencies-->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--spring-cloud-alibaba-dependencies-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--micrometer-tracing-bom-->
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-bom</artifactId>
                <version>${micrometer-tracing.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!--junit-->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <!--lombok-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <!--hutool-all-->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
        </dependency>
        <!--spring-boot-starter-test-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
    </dependencies>

</project>
